apiVersion: v1
kind: ServiceAccount
metadata:
  name: router-routes-load
  namespace: apps
  annotations:
    # Replace with ARN of IAM role created in previous step
    eks.amazonaws.com/role-arn: arn:aws:iam::<aws-account-id>:role/router-routes-load-<environment>
